### PR TITLE
Gm/update dokka

### PR DESCRIPTION
**Pull request by Megamiun**
Solves #152

### CODE REVIEW

**Comment by InsanusMokrassar** [comment]
@Megamiun mention me when it will be required to review PR:)

**Comment by Megamiun** [comment]
Oh, @InsanusMokrassar, ok!

And also, it's common for the "Pull Request Labeler / triage (pull_request)" to fail?

**Comment by InsanusMokrassar** [comment]
> Oh, @InsanusMokrassar, ok!
> 
> And also, it's common for the "Pull Request Labeler / triage (pull_request)" to fail?

If to be honest, it is suprise for me that greetings done correctly:) do not worry about it:)

**Comment by InsanusMokrassar** [comment]
I will review this PR asap

**Comment by InsanusMokrassar** [comment]
Unfortunatelly, I got next error:

```bash
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':docs:dokkaHtml'.
> Multiple pages associated with key: dev.inmo.tgbotapi.utils/MimeType///PointingToDeclaration//DisplaySourceSet(sourceSetIDs=CompositeSourceSetID(children=[:docs:dokkaHtml/jsMain]), name=js, platform=js)
```

I have used next command:

```bash
$ ./gradlew dokkaHtml
```

**Review by InsanusMokrassar — CHANGES_REQUESTED** [review]
It is required to keep Travis CI build passed. Currently it has been failed after `./gradlew dokkaHtml` command

**Comment by InsanusMokrassar** [comment]
I have updated master branch, you can pull changes to your pr and update `travis` config to use `dokkaHtml` tasj instead of just `dokka`

**Comment by Megamiun** [comment]
It seems that it is a addition to version 1.4.10:

https://github.com/Kotlin/dokka/pull/1177/files#diff-9f276aa180acf6c7fbf2d435e030eca0e7908922987578b0df420df7482e8561R39

Should I go back to 1.4.0, where this doesn't happen? It seems the problem is that only because we are trying to define the `expect class MimeType` on common and on any of the other two platforms and this causes an error.

**Comment by Megamiun** [comment]
@InsanusMokrassar It seems that it is a addition to version 1.4.10:

https://github.com/Kotlin/dokka/pull/1177/files#diff-9f276aa180acf6c7fbf2d435e030eca0e7908922987578b0df420df7482e8561R39

Should I go back to 1.4.0, where this doesn't happen? It seems the problem is that only because we are trying to define the expect class MimeType on common and on any of the other two platforms and this causes an error.

**Comment by InsanusMokrassar** [comment]
@Megamiun yes, I think, we can try to change version of dokka to 1.4.0

**Comment by Megamiun** [comment]
Hey, @InsanusMokrassar, it seems it is still trying to run the master configuration, with `./gradlew dokka`:

https://travis-ci.com/github/InsanusMokrassar/TelegramBotAPI/jobs/403753181#L475

**Comment by InsanusMokrassar** [comment]
> Hey, @InsanusMokrassar, it seems it is still trying to run the master configuration, with `./gradlew dokka`:
> 
> https://travis-ci.com/github/InsanusMokrassar/TelegramBotAPI/jobs/403753181#L475

It is related to current task config in master. I have checked it by myself and everything is ok, thank you:)

**Pull request merged**
